### ISSUE TITLE
YouTube history is not saved

### ISSUE THREAD

**Issue by yasinULLAH** [revancedapps/revancedmanager#6]
YouTube history is not saved and viewed video are also not remembered also there is no record of my YouTube in the Google activity page.

This is issue is also discuss in an another GitHub page/app
https://github.com/ReVanced/revanced-patches/issues/2779

**Comment by revancedapps** [comment]
Yes, this issue has been fixed based on the latest patch from the repository. 
However, because this patch does not support this newer YouTube version, so the update button is not shown on the Revanced.net Manager app. 
The easiest way to resolve this is to manually download the YT Revanced APK here [https://revanced.net/youtube-revanced#download-apk](https://revanced.net/youtube-revanced#download-apk) and install it override to the current version on your device. Rest assured, your current settings will be preserved, and the issue with the watch history will be fixed.

**Comment by yasinULLAH** [comment]
Revanced YouTube premium is fixed (the one with the red original YouTube icon) but revanced extended YouTube is till not fixed
